name: Deploy My App In DockerHub
on: [push]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Install node@16
    - uses: actions/setup-node@v3
      with:
        node-version: '16.3.0'
        check-latest: false
    - name: Install dependencies
    - run: npm ci
    - name: Build App
    - run: npm run build:prod
    - name: Deploy
    - run: echo Deploying...